### ISSUE TITLE
Make sure that all tutorials use lazyloading-style imports

### ISSUE THREAD

**Issue by lagru** [scipy-2023-image-analysis/tutorial#11]
Reminder and place to add what you think about this. See https://github.com/scikit-image/scikit-image/pull/7024.

**Comment by jni** [comment]
@lagru honestly I'm not super a fan of it... 😅 I'm too old-school. 😂  It's sort-of-ok in library code but it makes everything very verbose otherwise...

Incidentally I wonder whether `skim` is more evocative than `ski`...

**Comment by lagru** [comment]
Ha, I am in the opposite camp. :smile: I find having to go back to the boilerplate imports and having to add stuff as you go totally annoying. And I like the verbosity, e.g. no name clashes between SciPy's `signal` and some innocent 1-D array and its crystal clear where something is coming from at a glance. :heart_eyes: 

But totally fine with not doing it for this tutorial. We probably have more important stuff to update. :sweat_smile:
