### ISSUE TITLE
Adapt skimage's new inpainting example to tutorial?

### ISSUE THREAD

**Issue by lagru** [scipy-2023-image-analysis/tutorial#6]
Our Outreachy interns at scikit-image have been hard-working on a new gallery example for scikit-image https://github.com/scikit-image/scikit-image/pull/6853 ([current render](https://output.circle-artifacts.com/output/job/5eb0a5f0-0aa1-477e-bc2e-5ec0b7b8cdbc/artifacts/0/doc/build/html/auto_examples/applications/plot_cornea_spot_inpainting.html#sphx-glr-auto-examples-applications-plot-cornea-spot-inpainting-py)). I am thinking this could fit very nicely within an interactive tutorial. The dataset is "quite large" as skimage datasets go, so a nice opportunity for Napari to show it's muscles compared to plotly?

I am sure this would also totally motivate our Outreachy interns even more! :D

**Comment by jni** [comment]
@lagru I'm confused — where in the workshop schedule are you proposing to discuss this? The final "freeform" hour? For that I think we should have several options, including some small deep learning demos, plugins, a fast run through of advanced demos, or even just walking the room and interactively analysing students' data.

In the end I think inpainting is a bit too niche for the limited time that we have — I think it's very valuable for the website and library overall! But for a 4h tutorial you really want to hit the most common needs.

**Comment by lagru** [comment]
Hmm, I fear you are right. I think I had this idea "it includes segmentation" and thought it could maybe fit there as a shorter section. Thinking about it now, the tutorial is less about "see this cool new very specific thing" and more "see these cool libraries and problem domain". ^^
